version: '3'
services:
  web:
    build: .
    image: 'attack'
    networks:
      default:
        aliases:
          - attack-web
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: 'remote_host=host.docker.internal'
      PHP_IDE_CONFIG: 'serverName=localhost'
      DB_HOST: 'attack-database'
      DB_USER: 'attack'
      DB_PASSWORD: 'attack'
      DB_NAME: 'attack'
    volumes:
      - ../dist:/var/www/html/dist
      - ../php:/var/www/html/php
      - ../templates:/var/www/html/templates
      - ../vendor:/var/www/html/vendor
      - ../.htaccess:/var/www/html/.htaccess
      - ../favicon.ico:/var/www/html/favicon.ico
      - ../index.php:/var/www/html/index.php
      - ../public.key:/var/www/html/public.key
  database:
    image: 'mariadb:latest'
    networks:
      default:
        aliases:
          - attack-database
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'attack'
      MYSQL_USER: 'attack'
      MYSQL_PASSWORD: 'attack'
      MYSQL_DATABASE: 'attack'
    volumes:
      - ../mysqldumps:/docker-entrypoint-initdb.d
  php-my-admin:
    image: 'phpmyadmin/phpmyadmin:latest'
    networks:
      default:
        aliases:
          - attack-php-my-admin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: 'attack-database'
  composer-install:
    image: composer
    command: install --ignore-platform-reqs --no-scripts
    environment:
      COMPOSER_VENDOR_DIR: /var/www/vendor
    volumes:
      - ..:/var/www
    working_dir: /var/www
networks:
  default:
    driver: bridge
